targets:
    $default:
        builders:
            injectable_generator:injectable_builder:
                options:
                    auto_register: true
                    class_name_pattern: "Service$|Repository$|UseCase$|Bloc$"
                    package_names:
                        - flutter_users_app_new
